language: node_js
node_js:
  - "10"

cache:
  directories:
  - $HOME/.npm

before_install:
- export TZ='Asia/Shanghai' # 更改时区

install:
- npm install gitbook-cli -g
- npm install lint-md -g
- npm install
- gitbook install

script:
- gitbook build . ./build
- echo "http://odoobook.tnk-studio.org" > ./build/CNAME

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  name: travis@travis-ci.org
  email: Travis CI
  on:
    branch: master
